import type {
  AuditEvent,
  GigWorker,
  JobBatch,
  PayoutRecord,
  QAReviewItem,
  TaskItem,
} from "./types"

export const gigWorkers: GigWorker[] = [
  {
    id: "AG-001",
    name: "Ari Patel",
    role: "CX Specialist",
    region: "EMEA",
    timezone: "UTC+1",
    skills: ["chat support", "escalation handling", "sentiment tagging"],
    languages: ["English", "Hindi"],
    qualityScore: 97,
    availability: "available",
    workload: 2,
    maxWorkload: 6,
    hourlyRate: 28,
    bio: "Fast responder with strong de-escalation instincts and low defect rate.",
  },
  {
    id: "AG-002",
    name: "Mina Alvarez",
    role: "Data Labeler",
    region: "AMER",
    timezone: "UTC-5",
    skills: ["image labeling", "taxonomy QA", "annotation consistency"],
    languages: ["English", "Spanish"],
    qualityScore: 94,
    availability: "available",
    workload: 4,
    maxWorkload: 8,
    hourlyRate: 24,
    bio: "Detailed annotator with strong label discipline and review habits.",
  },
  {
    id: "AG-003",
    name: "Jordan Kim",
    role: "CX Generalist",
    region: "APAC",
    timezone: "UTC+9",
    skills: ["case triage", "chat support", "knowledge base updates"],
    languages: ["English", "Korean"],
    qualityScore: 91,
    availability: "busy",
    workload: 5,
    maxWorkload: 7,
    hourlyRate: 26,
    bio: "Good fit for mixed queues that need quick decisions and clean handoffs.",
  },
  {
    id: "AG-004",
    name: "Talia Green",
    role: "QA Reviewer",
    region: "EMEA",
    timezone: "UTC+0",
    skills: ["quality review", "policy checks", "annotation QA"],
    languages: ["English", "French"],
    qualityScore: 99,
    availability: "available",
    workload: 1,
    maxWorkload: 5,
    hourlyRate: 32,
    bio: "Reviews edge cases carefully and documents corrections clearly.",
  },
  {
    id: "AG-005",
    name: "Noah Singh",
    role: "Gig Worker",
    region: "AMER",
    timezone: "UTC-8",
    skills: ["transcription", "intent tagging", "feedback loops"],
    languages: ["English"],
    qualityScore: 88,
    availability: "available",
    workload: 3,
    maxWorkload: 6,
    hourlyRate: 22,
    bio: "Reliable for repetitive queues with high throughput needs.",
  },
  {
    id: "AG-006",
    name: "Priya Rao",
    role: "QA Reviewer",
    region: "APAC",
    timezone: "UTC+5:30",
    skills: ["policy checks", "sentiment tagging", "audit sampling"],
    languages: ["English", "Tamil"],
    qualityScore: 96,
    availability: "offline",
    workload: 0,
    maxWorkload: 4,
    hourlyRate: 30,
    bio: "Balances speed and correctness, especially for sensitive escalations.",
  },
]

export const jobs: JobBatch[] = [
  {
    id: "JOB-1001",
    clientName: "Northwind Care",
    title: "Support chat tagging wave",
    type: "cx",
    priority: "high",
    status: "in_progress",
    taskCount: 180,
    completedTaskCount: 126,
    qaPassRate: 96,
    dueDate: "2026-06-18",
    createdAt: "2026-06-14T08:00:00Z",
    notes: "Triaging billing, shipment, and cancellation chats with response-quality checks.",
    requiredSkills: ["chat support", "sentiment tagging", "escalation handling"],
  },
  {
    id: "JOB-1002",
    clientName: "Atlas Vision",
    title: "Product image labeling batch",
    type: "data-labeling",
    priority: "urgent",
    status: "qa",
    taskCount: 420,
    completedTaskCount: 401,
    qaPassRate: 91,
    dueDate: "2026-06-16",
    createdAt: "2026-06-13T10:15:00Z",
    notes: "High-volume bounding box and taxonomy labeling for a launch pipeline.",
    requiredSkills: ["image labeling", "taxonomy QA", "annotation consistency"],
  },
  {
    id: "JOB-1003",
    clientName: "Orbit Retail",
    title: "Returns triage and disposition",
    type: "cx",
    priority: "normal",
    status: "queued",
    taskCount: 96,
    completedTaskCount: 18,
    qaPassRate: 100,
    dueDate: "2026-06-19",
    createdAt: "2026-06-15T14:30:00Z",
    notes: "New queue with a mix of policy-sensitive and straightforward customer issues.",
    requiredSkills: ["case triage", "policy checks", "knowledge base updates"],
  },
  {
    id: "JOB-1004",
    clientName: "Signal Health",
    title: "Clinical intent review pilot",
    type: "data-labeling",
    priority: "high",
    status: "draft",
    taskCount: 72,
    completedTaskCount: 0,
    qaPassRate: 0,
    dueDate: "2026-06-21",
    createdAt: "2026-06-16T09:00:00Z",
    notes: "Awaiting client approval before dispatching work to the queue.",
    requiredSkills: ["intent tagging", "audit sampling", "policy checks"],
  },
]

export const tasks: TaskItem[] = [
  {
    id: "TASK-2001",
    jobId: "JOB-1001",
    title: "Label chat for refund request",
    type: "cx",
    priority: "high",
    status: "assigned",
    requiredSkills: ["chat support", "sentiment tagging"],
    estimatedMinutes: 8,
    assignedWorkerId: "AG-001",
    qaReviewer: "Talia Green",
    qualityScore: 98,
    payoutAmount: 2.4,
    dueAt: "2026-06-16T17:00:00Z",
    createdAt: "2026-06-16T09:30:00Z",
    notes: "High-priority customer complaint with positive resolution path.",
  },
  {
    id: "TASK-2002",
    jobId: "JOB-1001",
    title: "Escalation summary extraction",
    type: "cx",
    priority: "urgent",
    status: "in_review",
    requiredSkills: ["escalation handling", "case triage"],
    estimatedMinutes: 12,
    assignedWorkerId: "AG-003",
    qaReviewer: "Priya Rao",
    qualityScore: 92,
    payoutAmount: 3.2,
    dueAt: "2026-06-16T18:00:00Z",
    createdAt: "2026-06-16T10:10:00Z",
    notes: "Requires QA because the customer is flagged as sensitive.",
  },
  {
    id: "TASK-2003",
    jobId: "JOB-1002",
    title: "Front-facing product image box",
    type: "data-labeling",
    priority: "high",
    status: "approved",
    requiredSkills: ["image labeling", "annotation consistency"],
    estimatedMinutes: 5,
    assignedWorkerId: "AG-002",
    qaReviewer: "Talia Green",
    qualityScore: 99,
    payoutAmount: 1.8,
    dueAt: "2026-06-16T15:00:00Z",
    createdAt: "2026-06-15T11:30:00Z",
    notes: "Straight-through approved item with strong label fidelity.",
  },
  {
    id: "TASK-2004",
    jobId: "JOB-1002",
    title: "Taxonomy reconciliation pass",
    type: "data-labeling",
    priority: "normal",
    status: "correction_needed",
    requiredSkills: ["taxonomy QA", "policy checks"],
    estimatedMinutes: 14,
    assignedWorkerId: "AG-005",
    qaReviewer: "Priya Rao",
    qualityScore: 84,
    payoutAmount: 2.1,
    dueAt: "2026-06-16T16:30:00Z",
    createdAt: "2026-06-15T12:00:00Z",
    notes: "Needs a correction pass for label consistency.",
  },
  {
    id: "TASK-2005",
    jobId: "JOB-1003",
    title: "Returns intent triage",
    type: "cx",
    priority: "normal",
    status: "queued",
    requiredSkills: ["case triage", "knowledge base updates"],
    estimatedMinutes: 10,
    payoutAmount: 2.6,
    dueAt: "2026-06-17T11:00:00Z",
    createdAt: "2026-06-15T14:45:00Z",
    notes: "Awaiting assignment when the queue opens.",
  },
  {
    id: "TASK-2006",
    jobId: "JOB-1004",
    title: "Clinical intent label",
    type: "data-labeling",
    priority: "urgent",
    status: "escalated",
    requiredSkills: ["intent tagging", "policy checks"],
    estimatedMinutes: 9,
    assignedWorkerId: "AG-004",
    qaReviewer: "Priya Rao",
    qualityScore: 76,
    payoutAmount: 3,
    dueAt: "2026-06-16T19:30:00Z",
    createdAt: "2026-06-16T09:30:00Z",
    notes: "Escalated for policy review before release.",
  },
]

export const qaQueue: QAReviewItem[] = [
  {
    id: "QA-3001",
    taskId: "TASK-2002",
    jobId: "JOB-1001",
    reviewer: "Priya Rao",
    outcome: "escalated",
    reason: "Sensitive escalation requires senior review.",
    updatedAt: "2026-06-16T11:10:00Z",
  },
  {
    id: "QA-3002",
    taskId: "TASK-2004",
    jobId: "JOB-1002",
    reviewer: "Talia Green",
    outcome: "correction-needed",
    reason: "Label taxonomy mismatch on the secondary annotation layer.",
    updatedAt: "2026-06-16T11:35:00Z",
  },
  {
    id: "QA-3003",
    taskId: "TASK-2003",
    jobId: "JOB-1002",
    reviewer: "Talia Green",
    outcome: "approved",
    reason: "Labels aligned with the client guide and sample set.",
    updatedAt: "2026-06-16T10:55:00Z",
  },
]

export const payouts: PayoutRecord[] = [
  {
    id: "PAY-4001",
    taskId: "TASK-2003",
    workerId: "AG-002",
    amount: 1.8,
    status: "paid",
    scheduledFor: "2026-06-16",
    updatedAt: "2026-06-16T12:05:00Z",
  },
  {
    id: "PAY-4002",
    taskId: "TASK-2001",
    workerId: "AG-001",
    amount: 2.4,
    status: "queued",
    scheduledFor: "2026-06-16",
    updatedAt: "2026-06-16T12:10:00Z",
  },
  {
    id: "PAY-4003",
    taskId: "TASK-2002",
    workerId: "AG-003",
    amount: 3.2,
    status: "processing",
    scheduledFor: "2026-06-16",
    updatedAt: "2026-06-16T12:12:00Z",
  },
]

export const auditEvents: AuditEvent[] = [
  {
    id: "AUD-5001",
    timestamp: "2026-06-16T12:12:00Z",
    eventType: "payout.queued",
    actor: "system",
    entityType: "payout",
    entityId: "PAY-4002",
    summary: "Queued worker payout for task TASK-2001",
    details: "Approved task entered the daily payout batch.",
  },
  {
    id: "AUD-5002",
    timestamp: "2026-06-16T11:35:00Z",
    eventType: "qa.correction_needed",
    actor: "Talia Green",
    entityType: "review",
    entityId: "QA-3002",
    summary: "QA requested corrections on TASK-2004",
    details: "Reviewer flagged a taxonomy mismatch before release.",
  },
  {
    id: "AUD-5003",
    timestamp: "2026-06-16T11:10:00Z",
    eventType: "qa.escalated",
    actor: "Priya Rao",
    entityType: "review",
    entityId: "QA-3001",
    summary: "Sensitive review escalated for policy check",
    details: "Queue moved to senior review before worker payout.",
  },
  {
    id: "AUD-5004",
    timestamp: "2026-06-16T10:55:00Z",
    eventType: "qa.approved",
    actor: "Talia Green",
    entityType: "review",
    entityId: "QA-3003",
    summary: "TASK-2003 approved",
    details: "Approved work moved into payout eligibility.",
  },
  {
    id: "AUD-5005",
    timestamp: "2026-06-16T10:10:00Z",
    eventType: "task.assigned",
    actor: "orchestrator",
    entityType: "task",
    entityId: "TASK-2002",
    summary: "Assigned task to Jordan Kim",
    details: "Assignment balanced skill fit, availability, and queue priority.",
  },
  {
    id: "AUD-5006",
    timestamp: "2026-06-16T09:00:00Z",
    eventType: "job.created",
    actor: "client:Signal Health",
    entityType: "job",
    entityId: "JOB-1004",
    summary: "Created clinical intent review pilot",
    details: "Batch created in draft state awaiting approval.",
  },
]

export function getJobById(id: string | null | undefined): JobBatch | undefined {
  if (!id) return undefined
  return jobs.find((job) => job.id === id)
}

export function getTaskById(id: string | null | undefined): TaskItem | undefined {
  if (!id) return undefined
  return tasks.find((task) => task.id === id)
}

export function getWorkerById(id: string | null | undefined): GigWorker | undefined {
  if (!id) return undefined
  return gigWorkers.find((worker) => worker.id === id)
}